apiVersion: v1
kind: PersistentVolume
metadata:
  name: a-stock-market-environment-data
  labels:
    app.kubernetes.io/name: market-environment-data
    app.kubernetes.io/part-of: a-stock
    app.kubernetes.io/component: data-collection
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-local
  hostPath:
    path: /mnt/xiaomi/app-data/a-stock-market-environment
    type: Directory
  volumeMode: Filesystem