"""PostgreSQL schema bootstrap used by Alembic and local migrations.

The schema uses native PostgreSQL DATE, TIMESTAMPTZ and JSONB types. The
application boundary still canonicalizes JSON before checksumming, preserving
the legacy SQLite data-quality semantics.
"""

from __future__ import annotations

from sqlalchemy import Engine, text


SCHEMA_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS schema_migrations (
        version INTEGER PRIMARY KEY,
        name TEXT NOT NULL,
        applied_at TIMESTAMPTZ NOT NULL,
        checksum TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS snapshot_entries (
        dataset TEXT NOT NULL, as_of DATE NOT NULL, payload_json JSONB NOT NULL,
        source TEXT NOT NULL, status TEXT NOT NULL, observations INTEGER NOT NULL,
        warnings_json JSONB NOT NULL, fetched_at TIMESTAMPTZ NOT NULL, settled INTEGER NOT NULL DEFAULT 0,
        schema_version INTEGER NOT NULL, checksum TEXT NOT NULL, refresh_warning TEXT,
        PRIMARY KEY (dataset, as_of)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS refresh_leases (
        dataset TEXT NOT NULL, as_of DATE NOT NULL, owner TEXT NOT NULL,
        acquired_at TIMESTAMPTZ NOT NULL, expires_at TIMESTAMPTZ NOT NULL, generation INTEGER NOT NULL DEFAULT 0,
        token TEXT NOT NULL DEFAULT '', PRIMARY KEY (dataset, as_of)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS refresh_lease_fences (
        dataset TEXT NOT NULL, as_of DATE NOT NULL, generation INTEGER NOT NULL,
        token TEXT NOT NULL, updated_at TIMESTAMPTZ NOT NULL, PRIMARY KEY (dataset, as_of)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS lease_fence_events (
        event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        dataset TEXT NOT NULL, as_of DATE NOT NULL, owner TEXT NOT NULL,
        generation INTEGER NOT NULL, token TEXT NOT NULL, operation TEXT NOT NULL,
        reason TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS refresh_runs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        run_id TEXT NOT NULL, dataset TEXT NOT NULL, as_of DATE NOT NULL,
        result_json JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL,
        UNIQUE (run_id, dataset)
    )
    """,
    "CREATE INDEX IF NOT EXISTS refresh_runs_dataset_date_idx ON refresh_runs(dataset, as_of)",
    """
    CREATE TABLE IF NOT EXISTS collection_runs (
        run_id TEXT PRIMARY KEY, as_of DATE NOT NULL, status TEXT NOT NULL,
        requested_datasets_json JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL,
        started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS collection_tasks (
        task_id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES collection_runs(run_id),
        dataset TEXT NOT NULL, as_of DATE NOT NULL, status TEXT NOT NULL,
        source TEXT NOT NULL DEFAULT 'none', observations INTEGER NOT NULL DEFAULT 0,
        warning TEXT, timings_json JSONB NOT NULL DEFAULT '{}'::jsonb, queued_at TIMESTAMPTZ,
        started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, duration_ms DOUBLE PRECISION,
        settled INTEGER NOT NULL DEFAULT 0, UNIQUE(run_id, dataset)
    )
    """,
    "CREATE INDEX IF NOT EXISTS collection_tasks_dataset_date_idx ON collection_tasks(dataset, as_of, queued_at DESC)",
    """
    CREATE TABLE IF NOT EXISTS core_index_results (
        task_id TEXT NOT NULL REFERENCES collection_tasks(task_id), code TEXT NOT NULL,
        name TEXT NOT NULL, status TEXT NOT NULL, source TEXT NOT NULL DEFAULT 'none',
        observations INTEGER NOT NULL DEFAULT 0, warning TEXT, duration_ms DOUBLE PRECISION,
        payload_json JSONB, PRIMARY KEY(task_id, code)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS materialized_market_environment (
        as_of DATE PRIMARY KEY, payload_json JSONB NOT NULL, generated_at TIMESTAMPTZ NOT NULL, checksum TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS date_relabel_audits (
        audit_id TEXT PRIMARY KEY, source_as_of DATE NOT NULL, target_as_of DATE NOT NULL,
        status TEXT NOT NULL, operator TEXT NOT NULL, conflict_policy TEXT NOT NULL,
        plan_json JSONB NOT NULL, before_image_json JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL,
        applied_at TIMESTAMPTZ, rolled_back_at TIMESTAMPTZ, result_json JSONB
    )
    """,
    "CREATE INDEX IF NOT EXISTS date_relabel_audits_dates_idx ON date_relabel_audits(source_as_of, target_as_of, created_at)",
    """
    CREATE TABLE IF NOT EXISTS trading_sessions (
        as_of DATE PRIMARY KEY, previous_as_of DATE, actual_as_of DATE, is_session INTEGER NOT NULL,
        source TEXT NOT NULL, schema_version INTEGER NOT NULL, checksum TEXT NOT NULL,
        fetched_at TIMESTAMPTZ NOT NULL, warnings_json JSONB NOT NULL DEFAULT '[]'::jsonb
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS limit_security_datasets (
        as_of DATE PRIMARY KEY, actual_as_of DATE, source TEXT NOT NULL, source_revision TEXT,
        rule_version TEXT, schema_version INTEGER NOT NULL, complete INTEGER NOT NULL,
        membership_complete INTEGER, streak_complete INTEGER, pool_quality_json JSONB,
        excluded INTEGER NOT NULL DEFAULT 0, warnings_json JSONB NOT NULL DEFAULT '[]'::jsonb,
        dataset_checksum TEXT NOT NULL, fetched_at TIMESTAMPTZ NOT NULL
    )
    """,
    "ALTER TABLE limit_security_datasets ADD COLUMN IF NOT EXISTS membership_complete INTEGER",
    "ALTER TABLE limit_security_datasets ADD COLUMN IF NOT EXISTS streak_complete INTEGER",
    "ALTER TABLE limit_security_datasets ADD COLUMN IF NOT EXISTS pool_quality_json JSONB",
    """
    CREATE TABLE IF NOT EXISTS limit_security_facts (
        as_of DATE NOT NULL, actual_as_of DATE, security_id TEXT NOT NULL, pool_type TEXT NOT NULL,
        code TEXT NOT NULL, exchange TEXT NOT NULL, name TEXT, board TEXT, is_st INTEGER, is_new INTEGER,
        listing_date DATE, listing_days INTEGER, limit_regime TEXT, close_price DOUBLE PRECISION,
        previous_close DOUBLE PRECISION, change_pct DOUBLE PRECISION, touched_limit_up INTEGER,
        closed_limit_up INTEGER, failed_limit_up INTEGER, streak_days INTEGER,
        limit_up_time TEXT, limit_up_reason TEXT, seal_money DOUBLE PRECISION,
        max_seal_money DOUBLE PRECISION, first_limit_time TEXT, last_limit_time TEXT,
        open_times INTEGER, turnover_ratio_pct DOUBLE PRECISION, turnover DOUBLE PRECISION,
        row_quality TEXT, row_warnings_json JSONB NOT NULL DEFAULT '[]'::jsonb,
        eligible INTEGER NOT NULL, invalid_reason TEXT, source TEXT NOT NULL, fetched_at TIMESTAMPTZ NOT NULL,
        schema_version INTEGER NOT NULL, row_checksum TEXT NOT NULL, dataset_checksum TEXT,
        PRIMARY KEY(as_of, security_id, pool_type)
    )
    """,
    "ALTER TABLE limit_security_facts ADD COLUMN IF NOT EXISTS is_new INTEGER",
    "ALTER TABLE limit_security_facts ADD COLUMN IF NOT EXISTS limit_up_time TEXT",
    "ALTER TABLE limit_security_facts ADD COLUMN IF NOT EXISTS limit_up_reason TEXT",
    "ALTER TABLE limit_security_facts ADD COLUMN IF NOT EXISTS seal_money DOUBLE PRECISION",
    "ALTER TABLE limit_security_facts ADD COLUMN IF NOT EXISTS max_seal_money DOUBLE PRECISION",
    "ALTER TABLE limit_security_facts ADD COLUMN IF NOT EXISTS first_limit_time TEXT",
    "ALTER TABLE limit_security_facts ADD COLUMN IF NOT EXISTS last_limit_time TEXT",
    "ALTER TABLE limit_security_facts ADD COLUMN IF NOT EXISTS open_times INTEGER",
    "ALTER TABLE limit_security_facts ADD COLUMN IF NOT EXISTS turnover_ratio_pct DOUBLE PRECISION",
    "ALTER TABLE limit_security_facts ADD COLUMN IF NOT EXISTS turnover DOUBLE PRECISION",
    "ALTER TABLE limit_security_facts ADD COLUMN IF NOT EXISTS row_quality TEXT",
    "ALTER TABLE limit_security_facts ADD COLUMN IF NOT EXISTS row_warnings_json JSONB NOT NULL DEFAULT '[]'::jsonb",
    "CREATE INDEX IF NOT EXISTS limit_security_facts_date_security_idx ON limit_security_facts(as_of, security_id)",
    "CREATE INDEX IF NOT EXISTS limit_security_facts_eligible_idx ON limit_security_facts(as_of, eligible, closed_limit_up)",
    "CREATE INDEX IF NOT EXISTS limit_security_facts_pool_idx ON limit_security_facts(as_of, pool_type)",
    """
    CREATE TABLE IF NOT EXISTS materialization_component_versions (
        component_kind TEXT NOT NULL, dataset TEXT NOT NULL DEFAULT '', as_of DATE NOT NULL,
        revision INTEGER NOT NULL, PRIMARY KEY(component_kind, dataset, as_of)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS timezone_preferences (
        scope TEXT NOT NULL, subject_id TEXT NOT NULL, workspace_id TEXT NOT NULL DEFAULT '',
        timezone TEXT, updated_at TIMESTAMPTZ, PRIMARY KEY(scope, subject_id, workspace_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS provider_capability_reports (
        provider TEXT NOT NULL,
        dataset TEXT NOT NULL,
        revision TEXT NOT NULL,
        status TEXT NOT NULL,
        endpoint TEXT,
        field_coverage_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        date_evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        history_window_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        pagination_evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        permission_evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        rate_limit_evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        sample_count INTEGER NOT NULL DEFAULT 0,
        warnings_json JSONB NOT NULL DEFAULT '[]'::jsonb,
        missing_evidence_json JSONB NOT NULL DEFAULT '[]'::jsonb,
        checked_at TIMESTAMPTZ NOT NULL,
        schema_version INTEGER NOT NULL,
        checksum TEXT NOT NULL,
        PRIMARY KEY(provider, dataset, revision)
    )
    """,
    "CREATE INDEX IF NOT EXISTS provider_capability_reports_dataset_idx ON provider_capability_reports(dataset, checked_at DESC)",
    "CREATE INDEX IF NOT EXISTS provider_capability_reports_status_idx ON provider_capability_reports(dataset, status)",
    """
    CREATE TABLE IF NOT EXISTS timezone_preference_audit (
        audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        scope TEXT NOT NULL, subject_id TEXT NOT NULL, workspace_id TEXT NOT NULL DEFAULT '',
        actor_id TEXT NOT NULL, previous_timezone TEXT, timezone TEXT, changed_at TIMESTAMPTZ NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS timezone_preference_audit_lookup_idx ON timezone_preference_audit(scope, subject_id, workspace_id, audit_id)",
    """
    CREATE OR REPLACE FUNCTION bump_snapshot_component_revision() RETURNS trigger AS $$
    BEGIN
      INSERT INTO materialization_component_versions(component_kind, dataset, as_of, revision)
      VALUES ('snapshot', COALESCE(NEW.dataset, OLD.dataset), COALESCE(NEW.as_of, OLD.as_of), 1)
      ON CONFLICT(component_kind, dataset, as_of) DO UPDATE SET revision = materialization_component_versions.revision + 1;
      IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
      RETURN NEW;
    END; $$ LANGUAGE plpgsql
    """,
    """
    DO $$ BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'snapshot_component_revision_trigger') THEN
        CREATE TRIGGER snapshot_component_revision_trigger AFTER INSERT OR UPDATE OR DELETE ON snapshot_entries
        FOR EACH ROW EXECUTE FUNCTION bump_snapshot_component_revision();
      END IF;
    END $$
    """,
    """
    CREATE OR REPLACE FUNCTION bump_session_component_revision() RETURNS trigger AS $$
    BEGIN
      INSERT INTO materialization_component_versions(component_kind, dataset, as_of, revision)
      VALUES ('trading_session', '', COALESCE(NEW.as_of, OLD.as_of), 1)
      ON CONFLICT(component_kind, dataset, as_of) DO UPDATE SET revision = materialization_component_versions.revision + 1;
      IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
      RETURN NEW;
    END; $$ LANGUAGE plpgsql
    """,
    """
    DO $$ BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'session_component_revision_trigger') THEN
        CREATE TRIGGER session_component_revision_trigger AFTER INSERT OR UPDATE OR DELETE ON trading_sessions
        FOR EACH ROW EXECUTE FUNCTION bump_session_component_revision();
      END IF;
    END $$
    """,
    """
    CREATE OR REPLACE FUNCTION bump_limit_dataset_component_revision() RETURNS trigger AS $$
    BEGIN
      INSERT INTO materialization_component_versions(component_kind, dataset, as_of, revision)
      VALUES ('limit_dataset', '', COALESCE(NEW.as_of, OLD.as_of), 1)
      ON CONFLICT(component_kind, dataset, as_of) DO UPDATE SET revision = materialization_component_versions.revision + 1;
      IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
      RETURN NEW;
    END; $$ LANGUAGE plpgsql
    """,
    """
    DO $$ BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'limit_dataset_component_revision_trigger') THEN
        CREATE TRIGGER limit_dataset_component_revision_trigger AFTER INSERT OR UPDATE OR DELETE ON limit_security_datasets
        FOR EACH ROW EXECUTE FUNCTION bump_limit_dataset_component_revision();
      END IF;
    END $$
    """,
    """
    CREATE OR REPLACE FUNCTION bump_limit_facts_component_revision() RETURNS trigger AS $$
    BEGIN
      INSERT INTO materialization_component_versions(component_kind, dataset, as_of, revision)
      VALUES ('limit_facts', '', COALESCE(NEW.as_of, OLD.as_of), 1)
      ON CONFLICT(component_kind, dataset, as_of) DO UPDATE SET revision = materialization_component_versions.revision + 1;
      IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
      RETURN NEW;
    END; $$ LANGUAGE plpgsql
    """,
    """
    DO $$ BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'limit_facts_component_revision_trigger') THEN
        CREATE TRIGGER limit_facts_component_revision_trigger AFTER INSERT OR UPDATE OR DELETE ON limit_security_facts
        FOR EACH ROW EXECUTE FUNCTION bump_limit_facts_component_revision();
      END IF;
    END $$
    """,
)


def create_schema(engine: Engine) -> None:
    with engine.begin() as connection:
        # Several application workers can start at the same time during a
        # rollout. PostgreSQL serializes DDL through this transaction-scoped
        # advisory lock so the idempotent bootstrap cannot race on
        # CREATE/REPLACE FUNCTION or trigger creation.
        connection.execute(
            text("SELECT pg_advisory_xact_lock(hashtext('market-environment-schema-bootstrap'))")
        )
        for statement in SCHEMA_STATEMENTS:
            connection.execute(text(statement))
        connection.execute(
            text(
                """INSERT INTO schema_migrations(version, name, applied_at, checksum)
                   VALUES (4, 'postgresql-initial-schema', CURRENT_TIMESTAMP, 'postgresql-initial-schema')
                   ON CONFLICT(version) DO NOTHING"""
            )
        )
        connection.execute(
            text(
                """INSERT INTO schema_migrations(version, name, applied_at, checksum)
                   VALUES (5, 'add-limit-membership-and-detail-fields', CURRENT_TIMESTAMP,
                           'add-limit-membership-and-detail-fields')
                   ON CONFLICT(version) DO NOTHING"""
            )
        )
        connection.execute(
            text(
                """INSERT INTO schema_migrations(version, name, applied_at, checksum)
                   VALUES (6, 'add-provider-capability-reports', CURRENT_TIMESTAMP,
                           'add-provider-capability-reports')
                   ON CONFLICT(version) DO NOTHING"""
            )
        )
