apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: a-stock

resources:
  - namespace.yaml
  - persistent-volume-claim.yaml
  - deployment.yaml
  - market-data-collection-cronjob.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: a-stock-market-environment
    newName: a-stock-market-environment
    newTag: latest
