apiVersion: v1
kind: Service
metadata:
  name: market-environment-postgresql
  namespace: a-stock
  labels:
    app.kubernetes.io/name: market-environment-postgresql
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: market-environment-postgresql
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
