apiVersion: v1
kind: Service
metadata:
  name: market-environment-dashboard
  labels:
    app.kubernetes.io/name: market-environment-dashboard
    app.kubernetes.io/part-of: a-stock
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: market-environment-dashboard
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
